name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
    
      # Install Dependencies
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      # Build CarController
      - name: Build CarController
        run: |
          mkdir -p CarController/build
          cd CarController/build
          cmake -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake ..
          make

      # Build XboxController
      - name: Build XboxController
        run: |
          mkdir -p XboxController/build
          cd XboxController/build
          cmake -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake ..
          make

      # Set up Git user for tagging
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      # Generate Dynamic Tag (Optional)
      - name: Generate Version Tag
        id: version
        run: |
          echo "v$(date +'%Y%m%d%H%M')" > version_tag.txt
          echo "VERSION_TAG=$(cat version_tag.txt)" >> $GITHUB_ENV

      # Push Tags
      - name: Push Tag
        if: env.VERSION_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag $VERSION_TAG
          git push https://github.com/SEAME-pt/Team02-PyRacer.git --tags

      # Create Release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_TAG }}
          release_name: Release ${{ env.VERSION_TAG }}
          draft: false
          prerelease: false

      # Upload Release Assets
      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            CarController/build/CarController
            XboxController/build/XboxController
