name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
    
      # Install CMake
      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      # Install compilers
      - name: Install Compilers
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      # Build CarController
      - name: Build CarController
        run: |
          mkdir -p CarController/build
          cd CarController/build
          cmake -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake ..
          make

      # Build XboxController
      - name: Build XboxController
        run: |
          mkdir -p XboxController/build
          cd XboxController/build
          cmake -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake ..
          make

      # Create a tag (this step ensures there is always a tag before creating a release)
      - name: Create Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag v1.0.0  # Adjust this to use the versioning pattern you need
          git push origin v1.0.0

      # Create the GitHub Release and Upload Assets
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CarController/build/CarController
            XboxController/build/XboxController
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
