name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
    
      # Install CMake
      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      # Install compilers
      - name: Install Compilers
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      # Build CarController
      - name: Build CarController
        run: |
          mkdir -p CarController/build
          cd CarController/build
          cmake -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake ..
          make

      # Build XboxController
      - name: Build XboxController
        run: |
          mkdir -p XboxController/build
          cd XboxController/build
          cmake -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake ..
          make

      # Set up Git user for tagging
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      # Create a tag
      - name: Create Tag and Push
        run: |
          git tag v1.0.0  # Adjust the version to your needs
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SEAME-pt/Team02-PyRacer.git --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token to authenticate the push

      # Create GitHub release and upload assets
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CarController/build/CarController
            XboxController/build/XboxController
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
